version: '3'
services:
  workspace:
    container_name: workspace-chrisesplin.com
    build: ./dev/workspace
    ports:
      - '3001:3001'
      - '4000:4000'
      - '8080:8080'
    volumes:
      - './app:/app'
      - './docs:/app/docs'
