module.exports = {
  COLOSSAL: {
    name: 'Colossal',
    time: 'January - March 2020',
    hours: 197,
    contributors: ['@ChrisEsplin', '@Melissapher'],
    technologies: ['Firebase', 'BigQuery', 'Google Cloud Build', 'Docker', 'React', 'Next.js'],
    url: '/projects/colossal',
    projectUrl: 'https://www.colossal.tools',
    logotype: '/static/images/logotypes/colossal-logotype.png',
    logo: '/static/images/logos/colossal-logo.png',
  },
  HIIT_CLOCK: {
    name: 'HIIT Clock',
    time: 'February - September 2019',
    hours: 255,
    contributors: ['@ChrisEsplin'],
    technologies: ['Firebase', 'Google Cloud Build', 'Docker', 'React', 'Next.js'],
    url: '/projects/hiit-clock',
    projectUrl: 'https://www.hiitclock.com/',
    logo: '/static/images/logos/hiit-clock-logo.png',
    logotype: '/static/images/logotypes/hiit-clock-logotype.png',
  },
  PIXELS: {
    name: 'Pixels',
    time: 'December 2018 - February 2019',
    hours: 39,
    contributors: ['@ChrisEsplin'],
    technologies: ['Firebase', 'React', 'Chrome Extensions'],
    url: '/projects/pixels',
    projectUrl: 'https://pixels.chrisesplin.com/',
    logotype: '/static/images/logotypes/pixels-logotype.png',
    logo: '/static/images/logos/pixels-logo.png',
  },
  BUNCHES: {
    name: 'Bunches',
    time: 'December 2018',
    hours: 62,
    contributors: ['@ChrisEsplin'],
    technologies: ['Firebase', 'React', 'Next.js'],
    url: '/projects/bunches',
    projectUrl: 'https://bunches.chrisesplin.com/',
    logotype: '/static/images/logotypes/bunches-logotype.png',
    logo: '/static/images/logos/bunches-logo.png',
  },
  CALLIGRAPHY: {
    name: 'Calligraphy',
    time: 'July - November 2018',
    hours: 353,
    contributors: ['@ChrisEsplin', '@Melissapher'],
    technologies: ['Firebase', 'Shopify', 'GitHub', 'React', 'Next.js'],
    url: '/projects/calligraphy',
    projectUrl: 'https://www.calligraphy.org/',
    logotype: '/static/images/logotypes/calligraphy-logotype.png',
    logo: '/static/images/logos/calligraphy-logo.png',
  },
  FULL_STACK_FIREBASE: {
    name: 'Full-Stack Firebase',
    time: 'November 2017 - July 2018',
    hours: 479,
    contributors: ['@ChrisEsplin', '@JuarezPAF'],
    technologies: ['Firebase', 'Adobe Premiere', 'Adobe Audition'],
    url: '/projects/full-stack-firebase',
    projectUrl: 'https://www.fullstackfirebase.com/',
    logotype: '/static/images/logotypes/full-stack-firebase-logotype.png',
    logo: '/static/images/logos/full-stack-firebase-logo.png',
  },
  HOW_TO_FIREBASE: {
    name: 'How to Firebase',
    time: 'February 2016 - August 2018',
    hours: '> 100',
    contributors: ['@ChrisEsplin'],
    technologies: ['Firebase'],
    url: '/projects/how-to-firebase',
    projectUrl: 'https://howtofirebase.com/',
    logotype: '/static/images/logotypes/how-to-firebase-logotype.png',
    logo: '/static/images/logos/how-to-firebase-logo.png',
  },
  YOUTUBE: {
    name: 'YouTube',
    time: 'February 2016 - August 2018',
    hours: '> 200',
    contributors: ['@ChrisEsplin'],
    technologies: ['Firebase', 'Adobe Premiere', 'Adobe Audition'],
    url: '/projects/youtube',
    projectUrl: 'https://www.youtube.com/ChrisEsplin',
    logotype: '/static/images/logotypes/youtube-logotype.png',
    logo: '/static/images/logos/youtube-logo.png',
  },
};
